
[theme]
primaryColor="#1e3c72"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[server]
enableXsrfProtection = false
enableCORS = false

